name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: SuperStrongPassword
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET 9 SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.7'
        include-prerelease: true

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and start docker-compose
      run: |
        cd InternshipTask
        docker compose up -d --build

    - name: Wait for Postgres to be ready
      run: |
        until docker exec postgres pg_isready -U postgres; do
          echo "Waiting for Postgres..."
          sleep 2
        done

    - name: Run tests
      run: |
        dotnet test ./InternshipTask

    - name: Shutdown containers
      run: docker-compose down
